### ISSUE TITLE
LoggingManager.setLevel(LogLevel) has been deprecated

### ISSUE THREAD

**Issue by sergeykad** [iwarapter/gradle-sonar-packaging-plugin#14]
There is the following warning message on Gradle 2.14 during "pluginPackaging" task execution:
`LoggingManager.setLevel(LogLevel) has been deprecated and is scheduled to be removed in Gradle 3.0. If you are using this method to expose Ant logging messages, please use AntBuilder.setLifecycleLogLevel() instead.`

**Comment by iwarapter** [comment]
I have released 1.0-RC1 this has been fixed, can you give it a go please :)
