### ISSUE TITLE
Support `sonarQubeMinVersion` property

### ISSUE THREAD

**Issue by otrosien** [iwarapter/gradle-sonar-packaging-plugin#17]
In order to use current `6.x` APIs but remain compatibility with 5.6 LTS, we would need to specify this in the sonar manifest. See for example https://github.com/SonarSource/sonar-php/blob/master/pom.xml#L266

**Comment by iwarapter** [comment]
I have released 1.0-RC1 this support this property, can you give it a go please :)

**Comment by otrosien** [comment]
I think it was working when I tried. But I must admit that I recently switched to the shadow plugin from johnrengelman.
